---
ID: "9fefe107-cf50-4455-ba4b-6e5a02c63ac3"
Parent: "eefe4218-da20-4cb5-ac9a-be10854b49f8"
Template: "eefe4218-da20-4cb5-ac9a-be10854b49f8"
Path: /sitecore/templates/Project/HyattXM/HyattProduct/Rendering Parameters/ProductDetail/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "70c8243a-a999-4f97-831e-30bba78067ad"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gopi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240620T044035Z
