---
ID: "1d72cff3-0db6-4fe3-8a76-ed071f23ad96"
Parent: "f2004503-90eb-4033-9ded-10f0408ebcf1"
Template: "f2004503-90eb-4033-9ded-10f0408ebcf1"
Path: /sitecore/templates/Project/HyattXM/HyattProduct/ProductOffers Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{A4E5CAC9-22B3-4CEA-8AD3-897BE059DA5D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240620T051042Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\gopi@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\gopi@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4dc72284-b6bc-418b-9a0d-f945198b4aa8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gopi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240620T051057Z
