---
ID: "86d2aec7-c273-4c01-ae08-ba7527760095"
Parent: "1d058431-eaea-4fe6-bee4-965494415182"
Template: "1d058431-eaea-4fe6-bee4-965494415182"
Path: /sitecore/templates/Project/HyattXM/TestModule/Rendering Parameters/TestTeaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c257105-6ee0-43ec-8e9e-d1ada444fc9b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gopi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240613T175222Z
