---
ID: "d5953b81-1927-437e-916f-d6fb7019ef73"
Parent: "1081fa58-200d-4722-a51e-a5f7a79e5156"
Template: "1081fa58-200d-4722-a51e-a5f7a79e5156"
Path: /sitecore/templates/Project/HyattXM/TestModule/Rendering Parameters/TestPriceList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9e392ee0-4892-4fe1-9ab0-5264ddcd7525"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gopi@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240616T085929Z
